sonar.host.url=https://sonarcloud.io
sonar.coverage.jacoco.xmlReportPaths=./telematic_system/telematic_rsu_management_service/target/site/jacoco/jacoco.xml
sonar.exclusions=**/__init__.py,**/*test*.py,**/test/**,**/scripts/**,**/coverage/**,**/tests/**,**/scripts/**
sonar.coverage.exclusions=**/__init__.py,**/*test*.py,**/test/**,setup.py
sonar.java.binaries=./telematic_system/telematic_rsu_management_service/target/
sonar.javascript.lcov.reportPaths=./telematic_system/telematic_apps/web_app/coverage/lcov.info
sonar.modules=cloud_nats_bridge,ros2_nats_bridge,streets_nats_bridge,telematic_rsu_management_service,web_app_client,web_app_server,rosbag2_processing_service
sonar.organization=usdot-fhwa-stol
sonar.projectKey=usdot-fhwa-stol_cda-telematics
sonar.projectName=cda-telematics
sonar.scm.exclusions.disabled=true
sonar.verbose=true
sonar.python.coverage.reportPaths=./carma_cloud_bridge/coverage.xml,./carma_vehicle_bridge/coverage.xml,./telematic_system/telematic_historical_data_processing/rosbag2_processing_service/coverage.xml
sonar.python.version=3.9
cloud_nats_bridge.sonar.projectBaseDir=./telematic_system/telematic_units/carma_cloud_bridge/cloud_nats_bridge
cloud_nats_bridge.sonar.sources=src
cloud_nats_bridge.sonar.tests=test
ros2_nats_bridge.sonar.projectBaseDir=./telematic_system/telematic_units/carma_vehicle_bridge/ros2_nats_bridge
ros2_nats_bridge.sonar.sources=.
ros2_nats_bridge.sonar.tests=test
rosbag2_processing_service.sonar.projectBaseDir=./telematic_system/telematic_historical_data_processing/rosbag2_processing_service
rosbag2_processing_service.sonar.sources=.
rosbag2_processing_service.sonar.tests=test
streets_nats_bridge.sonar.projectBaseDir=./telematic_system/telematic_units/carma_street_bridge/streets_nats_bridge
streets_nats_bridge.sonar.sources=src
telematic_rsu_management_service.sonar.projectBaseDir=./telematic_system/telematic_rsu_management_service
telematic_rsu_management_service.sonar.sources=src/main/java
telematic_rsu_management_service.sonar.tests=src/test
telematic_rsu_management_service.sonar.test.inclusions=src/test/**
web_app_client.sonar.projectBaseDir=./telematic_system/telematic_apps/web_app/client
web_app_client.sonar.sources=src
web_app_client.sonar.tests=src/tests
web_app_server.sonar.projectBaseDir=./telematic_system/telematic_apps/web_app/server
web_app_server.sonar.sources=.
web_app_server.sonar.tests=tests