#!/bin/bash
# Builds .env from the deployment layers. Non-interactive: set ENVIRONMENT /
# TARGET / USE_CASE, and --yes to also run local.setup.sh unprompted.
set -euo pipefail

SYSTEM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SYSTEM_DIR}/.." && pwd)"
DEPLOYMENT_DIR="${REPO_ROOT}/deployment"
ENV_OUT="${SYSTEM_DIR}/.env"

ASSUME_YES=false
[[ "${1:-}" == "--yes" || "${1:-}" == "-y" ]] && ASSUME_YES=true

options_for() { find "${DEPLOYMENT_DIR}/$1" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort; }

prompt() {
  local layer="$1" default="$2" var="$3" choices reply
  choices="$(options_for "${layer}" | tr '\n' ' ')"
  reply="${!var:-}"
  if [[ -z "${reply}" ]] && [[ "${ASSUME_YES}" == false ]] && [[ -t 0 ]]; then
    read -rp "${layer} [${choices%% }] (${default}): " reply
  fi
  reply="${reply:-${default}}"
  if [[ ! -d "${DEPLOYMENT_DIR}/${layer}/${reply}" ]]; then
    echo "error: unknown ${layer} '${reply}'. Available: ${choices%% }" >&2
    exit 1
  fi
  printf '%s' "${reply}"
}

ENVIRONMENT="$(prompt environment dev ENVIRONMENT)"
TARGET="$(prompt targets on-premise TARGET)"
USE_CASE="$(prompt use_cases core USE_CASE)"

BASE_ENV="${SYSTEM_DIR}/sample.env"

LAYERS=(
  "${BASE_ENV}"
  "${DEPLOYMENT_DIR}/environment/${ENVIRONMENT}/.env"
  "${DEPLOYMENT_DIR}/targets/${TARGET}/.env"
  "${DEPLOYMENT_DIR}/use_cases/${USE_CASE}/.env"
)
for layer in "${LAYERS[@]}"; do
  [[ -f "${layer}" ]] || { echo "error: missing env file ${layer}" >&2; exit 1; }
done

echo
echo "environment : ${ENVIRONMENT}"
echo "target      : ${TARGET}"
echo "use case    : ${USE_CASE}"
echo

if [[ "${TARGET}" == "on-premise" ]]; then
  run_setup="${ASSUME_YES}"
  if [[ "${run_setup}" == false ]] && [[ -t 0 ]]; then
    echo "local.setup.sh edits /etc/hosts and deletes /opt/{grafana,apache2,influxdb2},"
    echo "discarding existing Grafana and InfluxDB data."
    read -rp "Run it? [y/N]: " reply
    [[ "${reply}" =~ ^[Yy]$ ]] && run_setup=true
  fi
  if [[ "${run_setup}" == true ]]; then
    ( cd "${SYSTEM_DIR}" && sudo ./local.setup.sh )
  else
    echo "Skipped local.setup.sh."
  fi
fi

# Compose takes the last definition of a duplicated key, so concatenating the
# layers in order gives the override behaviour.
{
  echo "# Generated by initialization.sh - edit the layers under deployment/ and re-run."
  echo "# environment=${ENVIRONMENT} target=${TARGET} use_case=${USE_CASE}"
  for layer in "${LAYERS[@]}"; do
    echo
    echo "##### ${layer#"${REPO_ROOT}/"} #####"
    cat "${layer}"
  done
} > "${ENV_OUT}"

echo "Wrote ${ENV_OUT}"
echo
if [[ "${USE_CASE}" == "rsu_integration" ]]; then
  echo "Next: docker compose --profile rsu_integration up -d"
else
  echo "Next: docker compose up -d"
fi
