services:
  nats:
    image: nats:2.10
    command: ["-DV"]
    network_mode: host
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rsm
      MYSQL_USER: telematic
      MYSQL_PASSWORD: telematic
    network_mode: host
    restart: unless-stopped
  
  influxdb3-core:
    image: influxdb:3.7.0-core
    user: "0:0"
    network_mode: host
    command:
    - influxdb3
    - serve
    - --node-id=node0
    - --object-store=file
    - --data-dir=/var/lib/influxdb3/data
    - --plugin-dir=/var/lib/influxdb3/plugins
    - --admin-token-file=/run/secrets/admin.token
    restart: unless-stopped
    secrets:
      - source: influx_admin_token
        target: /run/secrets/admin.token
    volumes:
      - influxdb3_data:/var/lib/influxdb3/data
      - influxdb3_plugins:/var/lib/influxdb3/plugins

  app:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    volumes:
      - ..:/workspace:cached
    network_mode: host
    depends_on:
      - nats
      - mysql
      - influxdb3-core
    env_file:
     - ../.env
    command: [ "sleep", "infinity" ]

  grafana:
    image: grafana/grafana:12.4.0-20117635118-ubuntu
    network_mode: host
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb3-core
    restart: unless-stopped
secrets:
  influx_admin_token:
    file: ./secrets/influx_admin_token.txt

volumes:
  influxdb3_data:
  influxdb3_plugins:
  grafana_data:
    

