#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
DEPLOYMENT_DIR="${REPO_ROOT}/deployment"
SYSTEM_DIR="${REPO_ROOT}/telematic_system"
ENV_OUT="${ENV_OUT:-${SYSTEM_DIR}/.env}"
MANIFEST_OUT="${MANIFEST_OUT:-${DEPLOYMENT_DIR}/generated/deployment_manifest.yml}"

require_variable() {
    local name="$1"

    if [[ -z "${!name:-}" ]]; then
        echo "error: ${name} is required." >&2
        exit 2
    fi
}

validate_configuration() {
    require_variable ENVIRONMENT
    require_variable TARGET
    require_variable USE_CASE

    local layers=(
        "${SYSTEM_DIR}/sample.env"
        "${DEPLOYMENT_DIR}/environment/${ENVIRONMENT}/.env"
        "${DEPLOYMENT_DIR}/targets/${TARGET}/.env"
        "${DEPLOYMENT_DIR}/use_cases/${USE_CASE}/.env"
    )

    local layer

    for layer in "${layers[@]}"; do
        if [[ ! -f "${layer}" ]]; then
            echo "error: missing configuration file ${layer}" >&2
            exit 2
        fi
    done
}

validate_required_secrets() {
    local secrets_dir="${SYSTEM_DIR}/secrets"
    local required_secrets=(
        "mysql_password.txt"
        "mysql_root_password.txt"
    )

    if [[ "${USE_CASE}" == "rsu_integration" ]]; then
        required_secrets+=("influx_admin_token.txt")
    fi

    local secret
    local failed=false

    for secret in "${required_secrets[@]}"; do
        if [[ ! -s "${secrets_dir}/${secret}" ]]; then
            echo "error: required secret file is missing or empty: ${secrets_dir}/${secret}" >&2

            if [[ -f "${secrets_dir}/${secret}.example" ]]; then
                echo "       create it from: ${secrets_dir}/${secret}.example" >&2
            fi

            failed=true
        fi
    done

    if [[ "${failed}" == true ]]; then
        exit 2
    fi

    echo "Required secrets validation: PASS"
}

generate_runtime_configuration() {
    local layers=(
        "${SYSTEM_DIR}/sample.env"
        "${DEPLOYMENT_DIR}/environment/${ENVIRONMENT}/.env"
        "${DEPLOYMENT_DIR}/targets/${TARGET}/.env"
        "${DEPLOYMENT_DIR}/use_cases/${USE_CASE}/.env"
    )

    local temp_file
    local layer

    temp_file="$(mktemp "${ENV_OUT}.tmp.XXXXXX")"

    trap 'rm -f "${temp_file}"' EXIT

    {
        echo "# Generated by deployment/scripts/configuration_service.sh"
        echo "# environment=${ENVIRONMENT} target=${TARGET} use_case=${USE_CASE}"

        for layer in "${layers[@]}"; do
            echo
            echo "##### ${layer#"${REPO_ROOT}/"} #####"
            cat "${layer}"
        done
    } > "${temp_file}"

    mv "${temp_file}" "${ENV_OUT}"
    trap - EXIT

    echo "Generated runtime configuration: ${ENV_OUT}"
}

generate_ansible_manifest() {
    local compose_profiles
    local manifest_dir
    local temp_file
    local runtime_env_path="${ENV_OUT#"${REPO_ROOT}/"}"

    compose_profiles="$(
        grep '^COMPOSE_PROFILES=' "${ENV_OUT}" \
            | tail -n 1 \
            | cut -d= -f2-
    )"

    if [[ -z "${compose_profiles}" ]]; then
        echo "error: COMPOSE_PROFILES is not defined in generated runtime configuration." >&2
        exit 2
    fi

    manifest_dir="$(dirname "${MANIFEST_OUT}")"
    mkdir -p "${manifest_dir}"

    temp_file="$(mktemp "${manifest_dir}/deployment_manifest.yml.tmp.XXXXXX")"
    trap 'rm -f "${temp_file}"' EXIT

    {
        echo "---"
        echo "environment: \"${ENVIRONMENT}\""
        echo "target: \"${TARGET}\""
        echo "use_case: \"${USE_CASE}\""
        echo "runtime_env_path: \"${runtime_env_path}\""
        echo "compose_manifest_paths:"
        echo "  - \"telematic_system/docker-compose.yml\""
        echo "compose_profiles:"

        IFS=',' read -ra profiles <<< "${compose_profiles}"

        local profile
        for profile in "${profiles[@]}"; do
            profile="${profile#"${profile%%[![:space:]]*}"}"
            profile="${profile%"${profile##*[![:space:]]}"}"
            echo "  - \"${profile}\""
        done
    } > "${temp_file}"

    mv "${temp_file}" "${MANIFEST_OUT}"
    trap - EXIT

    echo "Generated Ansible-compatible manifest: ${MANIFEST_OUT}"
}

main() {
    validate_configuration
    validate_required_secrets
    generate_runtime_configuration
    generate_ansible_manifest
}

main "$@"
