name: Docker build
on:
  pull_request:
    branches:
      - develop
      - master
      - 'release/**'
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  determine_docker_org_and_tag:
    runs-on: ubuntu-latest
    outputs:
      docker_organization: ${{ steps.docker-org-and-tag.outputs.docker_organization }}
      docker_image_tag: ${{ steps.docker-org-and-tag.outputs.docker_image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - id: docker-org-and-tag
        uses: usdot-fhwa-stol/actions/docker-org-and-tag@main

  telematic-apache:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: ./telematic_system/telematic_apps/apache2/
          file: ./telematic_system/telematic_apps/apache2/Dockerfile
          load: true
          tags: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_apache2:pr-${{ github.event.pull_request.number }}
      - name: Docker Scout Compare
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_apache2:pr-${{ github.event.pull_request.number }}
          to-env: ${{ needs.determine_docker_org_and_tag.outputs.docker_image_tag }}
          ignore-unchanged: true
          only-severities: critical,high
          organization: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}

  telematic-carma-cloud-nats-bridge:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: ./telematic_system/telematic_units/carma_cloud_bridge/
          file: ./telematic_system/telematic_units/carma_cloud_bridge/Dockerfile
          load: true
          tags: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/carma_cloud_nats_bridge:pr-${{ github.event.pull_request.number }}
      - name: Docker Scout Compare
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/carma_cloud_nats_bridge:pr-${{ github.event.pull_request.number }}
          to-env: ${{ needs.determine_docker_org_and_tag.outputs.docker_image_tag }}
          ignore-unchanged: true
          only-severities: critical,high
          organization: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}

  telematic-kafka-bridge:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: ./telematic_system/telematic_units/kafka_bridge/
          file: ./telematic_system/telematic_units/kafka_bridge/Dockerfile
          load: true
          tags: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/carma_street_nats_bridge:pr-${{ github.event.pull_request.number }}
      - name: Docker Scout Compare
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/carma_street_nats_bridge:pr-${{ github.event.pull_request.number }}
          to-env: ${{ needs.determine_docker_org_and_tag.outputs.docker_image_tag }}
          ignore-unchanged: true
          only-severities: critical,high
          organization: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}

  telematic-carma-vehicle-bridge:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: ./telematic_system/telematic_units/carma_vehicle_bridge/
          file: ./telematic_system/telematic_units/carma_vehicle_bridge/Dockerfile
          load: true
          tags: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/carma_vehicle_nats_bridge:pr-${{ github.event.pull_request.number }}
      - name: Docker Scout Compare
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/carma_vehicle_nats_bridge:pr-${{ github.event.pull_request.number }}
          to-env: ${{ needs.determine_docker_org_and_tag.outputs.docker_image_tag }}
          ignore-unchanged: true
          only-severities: critical,high
          organization: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}

  telematic-historical-data-processing:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: ./telematic_system/telematic_historical_data_processing/
          file: ./telematic_system/telematic_historical_data_processing/Dockerfile
          load: true
          tags: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_historical_data_processing:pr-${{ github.event.pull_request.number }}
      - name: Docker Scout Compare
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_historical_data_processing:pr-${{ github.event.pull_request.number }}
          to-env: ${{ needs.determine_docker_org_and_tag.outputs.docker_image_tag }}
          ignore-unchanged: true
          only-severities: critical,high
          organization: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}

  telematic-grafana:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: ./telematic_system/telematic_apps/grafana/
          file: ./telematic_system/telematic_apps/grafana/Dockerfile
          load: true
          tags: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_grafana:pr-${{ github.event.pull_request.number }}
      - name: Docker Scout Compare
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_grafana:pr-${{ github.event.pull_request.number }}
          to-env: ${{ needs.determine_docker_org_and_tag.outputs.docker_image_tag }}
          ignore-unchanged: true
          only-severities: critical,high
          organization: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}

  telematic-cloud-messaging:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: ./telematic_system/telematic_cloud_messaging/
          file: ./telematic_system/telematic_cloud_messaging/Dockerfile
          load: true
          tags: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_cloud_messaging:pr-${{ github.event.pull_request.number }}
      - name: Docker Scout Compare
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_cloud_messaging:pr-${{ github.event.pull_request.number }}
          to-env: ${{ needs.determine_docker_org_and_tag.outputs.docker_image_tag }}
          ignore-unchanged: true
          only-severities: critical,high
          organization: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}

  telematic-rsu-management-service:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: ./telematic_system/telematic_rsu_management_service/
          file: ./telematic_system/telematic_rsu_management_service/Dockerfile
          load: true
          tags: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_rsu_management_service:pr-${{ github.event.pull_request.number }}
      - name: Docker Scout Compare
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_rsu_management_service:pr-${{ github.event.pull_request.number }}
          to-env: ${{ needs.determine_docker_org_and_tag.outputs.docker_image_tag }}
          ignore-unchanged: true
          only-severities: critical,high
          organization: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}

  telematic-web-app-client:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: ./telematic_system/telematic_apps/web_app/client/
          file: ./telematic_system/telematic_apps/web_app/client/Dockerfile
          load: true
          tags: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_web_client:pr-${{ github.event.pull_request.number }}
      - name: Docker Scout Compare
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_web_client:pr-${{ github.event.pull_request.number }}
          to-env: ${{ needs.determine_docker_org_and_tag.outputs.docker_image_tag }}
          ignore-unchanged: true
          only-severities: critical,high
          organization: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}

  telematic-web-app-server:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: ./telematic_system/telematic_apps/web_app/server/
          file: ./telematic_system/telematic_apps/web_app/server/Dockerfile
          load: true
          tags: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_web_server:pr-${{ github.event.pull_request.number }}
      - name: Docker Scout Compare
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/telematic_web_server:pr-${{ github.event.pull_request.number }}
          to-env: ${{ needs.determine_docker_org_and_tag.outputs.docker_image_tag }}
          ignore-unchanged: true
          only-severities: critical,high
          organization: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}